goods/urls.py
from django.urls import path
from goods.views import GoodsListView, ProductDetailView

app_name = 'goods'

urlpatterns = [
    path('', GoodsListView.as_view(), name='index'),
    path('product/', ProductDetailView.as_view(), name='product')
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from goods.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('catalog/', include('goods.urls', namespace='goods')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import UsersLoginView

app_name = 'users'

urlpatterns = [
    path('login/', UsersLoginView.as_view(), name='login'),
    # path('registration/', UsersRegisterView.as_view(), name='register')
]

goods/models.py
from django.db import models


class GoodsCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Goods(models.Model):
    image = models.ImageField(upload_to='products_image')
    name = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    category = models.ForeignKey(to=GoodsCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'Имя товара: {self.name} | Цена товара: {self.price}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'from-control', 'placeholder': 'Введите ваше имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control", 'placeholder': 'Введите ваш пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')

goods/views.py
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from goods.models import Goods
from django.http import HttpResponse
from django.shortcuts import render


class IndexView(TemplateView):
    template_name = 'goods/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data()
        context['title'] = 'Home'
        return context


class GoodsListView(ListView):
    template_name = 'goods/catalog.html'
    model = Goods

    def get_context_data(self, **kwargs):
        context = super(GoodsListView, self).get_context_data()
        context['title'] = 'Goods'
        return context


class ProductDetailView(ListView):
    template_name = 'goods/product.html'
    model = Goods

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data()
        context['title'] = 'Product'
        return context

users/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView

from users.forms import UserLoginForm


class UsersLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm


# class UsersRegisterView(LoginView):
#     template_name = 'users/registration.html'

goods/templates/goods/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %} {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Про нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'users:login' %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="users/profile.html">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static 'deps/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        <li><a class="dropdown-item text-white" href="{% url 'goods:index' %}">Все товары</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Кухня</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Спальня</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Гостинная</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Офис</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Фурнитура</a></li>
                        <li><a class="dropdown-item text-white" href="catalog.html">Декор</a></li>
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static 'deps/icons/trash3-fill.svg' %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        {% block content %}
        {% endblock %}
    </section>
    {% block footer %}
    {% endblock %}
    
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/jquery-events.js' %}"></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

goods/templates/goods/catalog.html
{% extends 'goods/base.html' %}
{% load static %}

{% block css %}
	<link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
{% endblock %}
    
<!-- Контент -->
{% block content %}
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Пустой блок на усмотрение -->
            </div>
            <div class="col-lg-10">
                <!-- Контент на странице -->
                <div class="row">
                    <!-- Форма фильтров -->
                    <div class="dropdown mb-2">
                        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Фильтры
                        </button>
                
                        <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                                <input type="hidden" name="q" value="request.GET.q">
                                <label class="form-check-label" for="flexCheckDefault">
                                    Товары по акции
                                </label>
                            </div>
                            <p class="text-white mx-3 mt-3">Сортировать:</p>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                                <label class="form-check-label" for="flexRadioDefault1">
                                    По умолчанию
                                </label>
                            </div>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                                <label class="form-check-label" for="flexRadioDefault2">
                                    От дешевых к дорогим
                                </label>
                            </div>
                            <div class="form-check text-white mx-3">
                                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                                <label class="form-check-label" for="flexRadioDefault3">
                                    От дорогих к дешевым
                                </label>
                            </div>
                            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                        </form>
                    </div>
                    <!-- Карта товара -->
                    {% if object_list %}
                    {% for goods in object_list %}
                        <div class="col-lg-4 col-md-6 p-4">
                            <div class="card border-primary rounded custom-shadow">
                                <img src="{{ goods.image.url }}" class="card-img-top" alt="...">
                                <div class="card-body">
                                    <a href="{% url 'goods:product' %}">
                                        <p class="card-title">{{ goods.name }}</p>
                                    </a>
                                    <p class="card-text text-truncate">{{ goods.description }}</p>
                                    <p class="product_id">id: {{goods.id }}</p>
                                    <div class="d-flex justify-content-between">
                                        {% if goods.sale_price == 0 %}
                                            <p><strong>{{ goods.price }} $</strong></p>
                                        {% else %}
                                            <p><s>{{ goods.price }} $</s></p>
                                            <p><strong>{{ goods.sale_price }} $</strong></p>
                                            <span class="badge bg-warning text-dark">Sale</span>
                                        {% endif %} 
                                            <!-- <p><strong>100.00 $</strong></p> -->
                                            <a href="#" class="btn add-to-cart">
                                                <img class="mx-1" src="{% static 'deps/icons/cart-plus.svg' %}" alt="Catalog Icon"
                                                    width="32" height="32">
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    {% else %}
                        <h4 class="mt-3 mb-3 text-right">
                            Нет товаров!
                            <img width="400" height="400" src="{% static 'deps/images/chart.png' %}">
                        </h4>
                    {% endif %}
                </div>
                <!-- Пагинация -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center my-4">
                        <div class="custom-shadow d-flex">
                            <li class="page-item disabled">
                              <a class="page-link">Previous</a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                              <a class="page-link" href="#">Next</a>
                            </li>
                        </div>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}    
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock %}

goods/templates/goods/index.html
{% extends 'goods/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
{% endblock %}

{% block content %}
    <!-- Контент -->
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Пустой блок на Ваше усмотрение -->
            </div>
            <div class="col-lg-10">
                <!-- Контент на странице -->
                <h1 class="mt-5 pt-5"><strong>Магазин мебели HOME</strong></h1>
            </div>
        </div>
    </div>
{% endblock %}

{% block footer %}
	<footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock %}

goods/templates/goods/product.html
{% extends 'goods/base.html' %}
{% load static %}

{% block content %}
    <!-- Контент -->
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Пустой блок на усмотрение -->
            </div>
            <div class="col-lg-10">
                <!-- Контент на странице -->
                <div class="container mt-5">
                    <div class="card mb-4 custom-shadow">
                        <div class="row">
                            <!-- Миниатюры -->
                            <div class="col-md-4">
                                <img src="{{ goods.image.url }}"
                                    class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                            </div>
                            <div class="col-md-4 ">
                                <p class="product_id mt-3">id: {{ goods.id }}</p>
                            </div>
                            <!-- Увеличить изображение в модальном окне -->
                            <div class="modal fade" id="imageModal1" tabindex="-1"
                                aria-labelledby="imageModal1Label" aria-hidden="true">
                                <div class="modal-dialog modal-lg">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Закрыть"></button>
                                        </div>
                                        <div class="modal-body">
                                            <img src="{{ goods.image.url }}"
                                                class="img-fluid" alt="Изображение 1">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Описание товара -->
                        <div class="card-body">
                            <p class="card-text"><strong>Цена: {{ goods.price }} $</strong></p>
                            <h5 class="card-title">{{ goods.name }}</h5>
                            <p class="card-text">{{ goods.description }}</p>
                            <a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'goods/base.html' %}
{% load static %}

{% block content %}
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'users:login' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="{{ form.username.id_for_lable }}" class="form-label">
                                Имя пользователя
                            </label>
                            {{ form.username }}
                        </div>
                        <div class="mb-3">
                            <label for="{{ form.password.id_for_lable }}" class="form-label">
                                Пароль
                            </label>
                            {{ form.password }}
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="#">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'goods/base.html' %}
{% load static %}

{% block content %}
    <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    <div class="row">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                    <h2 class="text-center mb-4">Регистрация</h2>
                                    <form method = post>
                                    {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="firstName" class="form-label">Имя*</label>
                                                <input type="text" class="form-control" id="firstName"
                                                    placeholder="Введите ваше имя" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="lastName" class="form-label">Фамилия*</label>
                                                <input type="text" class="form-control" id="lastName"
                                                    placeholder="Введите вашу фамилию" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="username" class="form-label">Имя пользователя*</label>
                                                <input type="text" class="form-control" id="username"
                                                    placeholder="Введите ваше имя пользователя" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="email" class="form-label">Email*</label>
                                                <input type="email" class="form-control" id="email"
                                                    placeholder="Введите ваш email" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="password1" class="form-label">Пароль*</label>
                                                <input type="password" class="form-control" id="password1"
                                                    placeholder="Введите пароль" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="password2" class="form-label">Подтверждение пароля*</label>
                                                <input type="password" class="form-control" id="password2"
                                                    placeholder="Подтвердите пароль" required>
                                            </div>
                                        </div>
                                        <button type="submit"
                                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}